repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
        exclude: ^\.vscode/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^(src|test)/.*\.py$
        args: [--exclude, alembic/]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
        exclude: ^(tests|docs|alembic|data|uploads)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        additional_dependencies: [ pydantic, types-requests, sqlalchemy ]
        args: [ 
          --python-version=3.12, 
          --strict,
          --warn_return_any,          
          --warn-unused-configs, 
          --warn_redundant_casts,
          --warn_unused_ignores,
          --no_implicit_reexport,
          --ignore-missing-imports 
        ]
        exclude: ^(tests|docs|alembic|data|uploads)/