repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
        exclude: ^\.vscode/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^(src|tests)/.*\.py$
        args: [--exclude, alembic/]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
        exclude: ^(tests|docs|alembic|data|uploads)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [ pydantic, types-requests, sqlalchemy, types-boto3 ]
        args: [
          --python-version=3.12,
          --strict,
          --warn-return-any,
          --warn-unused-configs,
          --warn-redundant-casts,
          --warn-unused-ignores,
          --no-implicit-reexport,
          --ignore-missing-imports
        ]
        exclude: ^(tests|docs|alembic|data|uploads)/
